Issue 4 - https://github.com/thenewguy/django-allauth-adfs/issues/4
thenewguy/django-allauth-adfs pull request #5
Opened 2022-09-15 16:38 UTC by mattloomis

Fix for Issue 4 - https://github.com/thenewguy/django-allauth-adfs/issues/4

This PR gets the signature method algorithm from the Federation Metadata XML, and sends it to the JWT signature verification method if it is required (for jwt lib > 2.x)

2022-09-15 18:34 UTC, thenewguy requested changes
We should probably update the cache key to include `JWT_ALGORITHM_REQUIRED` since the format of the cache value changed

2022-09-15 19:21 UTC, mattloomis commented
> We should probably update the cache key to include `JWT_ALGORITHM_REQUIRED` since the format of the cache value changed

Hmm, in this PR, it would _always_ get the signing method algorithm and _always_ store a `dict` (with both the key bytes and any detected 'supported' algorithm) in the cache regardless of the value of `JWT_ALGORITHM_REQUIRED`.  When verifying the JWT signature it would _always_ get the `dict` back out of the cache, but conditionally send the "supported algorithms" list to the `jwt.decode()` when `JWT_ALGORITHM_REQUIRED` is true.

I could be misunderstanding your comment though. Happy to include the value of `JWT_ALGORITHM_REQUIRED` in the cache key string, but I don't think that being true/false will has an impact on what is in the cache?  Also assuming that if someone is updating the version of the `jwt` library (or really updating the version of this `django-allauth-adfs` library that uses this new approach), the entire process is being restarted and the cache is starting from empty, so there wouldn't be a concern of an old cache value (only the `key` bytes, not a `dict`) being returned to this new code?

2022-09-15 19:33 UTC, thenewguy commented
> Also assuming that if someone is updating the version of the `jwt` library (or really updating the version of this `django-allauth-adfs` library that uses this new approach), the entire process is being restarted and the cache is starting from empty, so there wouldn't be a concern of an old cache value (only the `key` bytes, not a `dict`) being returned to this new code?

Yes I am talking about upgrading. The cache is currently full of public keys. For some sites this is used on, upgrading to a new version won't necessarily purge the cache - so they would end up with the `key` bytes, not a `dict` and break.

2022-09-15 19:40 UTC, mattloomis commented
> > Also assuming that if someone is updating the version of the `jwt` library (or really updating the version of this `django-allauth-adfs` library that uses this new approach), the entire process is being restarted and the cache is starting from empty, so there wouldn't be a concern of an old cache value (only the `key` bytes, not a `dict`) being returned to this new code?
> 
> Yes I am talking about upgrading. The cache is currently full of public keys. For some sites this is used on, upgrading to a new version won't necessarily purge the cache - so they would end up with the `key` bytes, not a `dict` and break.

Ah... Now I see that the `cache` is the Django cache.. so yeah, could be using Redis/DB/etc. gotcha.  Instead of trying to `JWT_ALGORITHM_REQUIRED`, maybe it is useful to introduce a general `CACHE_VALUE_FORMAT_VERSION = "v1"` attribute and then use that in the cache key string like:

```
        cache_key = ":".join([
            "allauth_adfs",
            "ADFSOAuth2Adapter",
            CACHE_VALUE_FORMAT_VERSION,
            md5(hashable_url).hexdigest(),
            "token_signature_key",
        ])
```
In case the cache value format changes again in a future version, this could just be incremented to `CACHE_VALUE_FORMAT_VERSION = "v2"`, etc.?

2022-09-15 19:50 UTC, thenewguy commented
> In case the cache value format changes again in a future version, this could just be incremented to `CACHE_VALUE_FORMAT_VERSION = "v2"`, etc.?

That works!

2022-09-16 11:01 UTC, thenewguy commented
@mattloomis I took another look this morning and realized the "version" token that we added is unnecessary. Was busy yesterday and didn't have an opportunity to read the file as a whole.

Let's revert the `CACHE_VALUE_FORMAT_VERSION` change.  We should change
```
        cache_key = ":".join([
            "allauth_adfs",
            "ADFSOAuth2Adapter",
            md5(hashable_url).hexdigest(),
            "token_signature_key",
        ])
```
to
```
        cache_key = ":".join([
            "allauth_adfs",
            "ADFSOAuth2Adapter",
            md5(hashable_url).hexdigest(),
            "token_signature",
        ])
```
since you changed the property from `token_signature_key` to `token_signature` and that resolves the issue.

Let me know this works for you in a production environment and I will merge.  Thanks for your contribution!

2022-09-16 11:02 UTC, thenewguy approved these changes

2022-09-16 11:03 UTC, thenewguy requested changes
See https://github.com/thenewguy/django-allauth-adfs/pull/5/#issuecomment-1249227882

2022-09-16 16:24 UTC, mattloomis commented
> 
> since you changed the property from `token_signature_key` to `token_signature` and that resolves the issue.
> 
> Let me know this works for you in a production environment and I will merge. Thanks for your contribution!

Make sense to me.  Made the update.

The code prior to this last `token_signature_key` -> `token_signature` change has been working in a production environment already.

Let me know if you need anything else from me.  Thanks for starting this lib in the first place!

2022-09-16 16:37 UTC, merged

2022-09-16 16:42 UTC, mattloomis commented
@thenewguy - 💯 . Do you have a cadence of when you would publish a new package version to pypi?

2022-09-16 17:27 UTC, thenewguy commented
@mattloomis published now